# Generated by Django 3.1.7 on 2021-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Laukiama', 'Laukiama'), ('Išvežta pristatymui', 'Išvežta pristatymui'), ('Pristatyta', 'Pristatyta')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Tapyba', 'Tapyba'), ('Grafika', 'Grafika')], max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
